export const SET_USER = "SET_USER"
export const REMOVE_USER = "REMOVE_USER"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_CART = "REMOVE_CART"
export const CHANGE_AMOUNT = "CHANGE_AMOUNT"
export const DELETE_CART = "DELETE_CART"
