export const HOME_PAGE = "/"
export const ABOUT_PAGE = "/about"
export const SIGN_IN_PAGE = "/sign-in"
export const SIGN_UP_PAGE = "/sign-up"
export const PRODUCTS_PAGE = "/products"
export const PROFILE_PAGE = "/profile"
export const CART_PAGE = "/cart"
export const WRONG_PATH = "*"
